### ISSUE TITLE
Peer to peer code Review

### ISSUE THREAD

**Issue by Yorsyboy** [khitermedachraf/my-professional-portfolio#12]
Hi @khitermedachraf  you've done a great job so far 💯  but some suggestions from the team

- It will be great if you use one javascript file for all event listeners.
- You can also use one CSS file for all styling purposes.
- Instead of repetition of some code in your js file, you can iterate like a FOREACH loop

Happy Coding 👍

**Comment by khitermedachraf** [comment]
Ahh, **Thank you so much** for these useful suggestions. 

- I will take them into consideration in the next milestones.
